export const books = [
  {
    id: 1,
    imgsrc: "https://m.media-amazon.com/images/I/61Iz2yy2CKL._AC_UY218_.jpg",
    title: "The Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    genre: "Self-help",
    year: "2003",
    price: 90,
    booksavailable: "2",
  },
  {
    id: 2,
    imgsrc: "https://m.media-amazon.com/images/I/71zytzrg6lL._AC_UY218_.jpg",
    title: "The 5 AM Club",
    author: "Robin Sharma",
    genre: "Self-help",
    year: "2018",
    price: 60,
    booksavailable: "6",
  },
  {
    id: 3,
    imgsrc: "https://m.media-amazon.com/images/I/718QOMOhIQL._AC_UY218_.jpg",
    title: "Better Than Best Friends",
    author: "Ahona Sadhu",
    genre: "Short story",
    year: "2020",
    price: 100,
    booksavailable: "3",
  },
  {
    id: 4,
    imgsrc: "https://m.media-amazon.com/images/I/51gLHrowgBL._AC_UY218_.jpg",
    title: "Physical Chemistry",
    author: "Rajiv",
    genre: "Science",
    year: "2022",
    price: 100,
    booksavailable: "10",
  },
  {
    id: 5,
    imgsrc: "https://m.media-amazon.com/images/I/61pHaR-LO6L._AC_UY218_.jpg",
    title: "Excel Formulas",
    author: "Michael Alexander",
    genre: "Computer",
    year: "2019",
    price: 85,
    booksavailable: "5",
  },
  {
    id: 6,
    imgsrc: "https://m.media-amazon.com/images/I/81b1PP4RK1L._AC_UY218_.jpg",
    title: "That Night",
    author: "Nidhi Upadhyay",
    genre: "Novel",
    year: "2021",
    price: 110,
    booksavailable: "1",
  },
  {
    id: 7,
    imgsrc: "https://m.media-amazon.com/images/I/71TQiECAkKL._AC_UY218_.jpg",
    title: "Hidden Hindu",
    author: "Akshat gupta",
    genre: "Novel",
    year: "2021",
    price: 90,
    booksavailable: "4",
  },
  {
    id: 8,
    imgsrc: "https://m.media-amazon.com/images/I/61eFRZCBBXL._AC_UY218_.jpg",
    title: "Naruto",
    author: "Masashi Kishimoto",
    genre: "Comics",
    year: "2010",
    price: 150,
    booksavailable: "1",
  },
  {
    id: 9,
    imgsrc: "https://m.media-amazon.com/images/I/91oJaijImVL._AC_UY218_.jpg",
    title: "The Boken Ear",
    author: "Herge",
    genre: "Comics",
    year: "2013",
    price: 120,
    booksavailable: "4",
  },
  {
    id: 10,
    imgsrc: "https://m.media-amazon.com/images/I/61dMTFfkh1L._AC_UY218_.jpg",
    title: "Handbook of Electrical Engineering",
    author: "S.L. Bhatia",
    genre: "Engineering",
    year: "2019",
    price: 100,
    booksavailable: "10",
  },
  {
    id: 11,
    imgsrc: "https://m.media-amazon.com/images/I/410kATHUoML._AC_UY218_.jpg",
    title: "IT Project Management",
    author: "Joseph Phillips",
    genre: "Engineering",
    year: "2017",
    price: 90,
    booksavailable: "5",
  },
  {
    id: 12,
    imgsrc:
      "https://m.media-amazon.com/images/I/51HfkDbya7L._SX378_BO1,204,203,200_.jpg",
    title: "HTML and CSS",
    author: "Thomas Powell",
    genre: "Computer",
    year: "2013",
    price: 65,
    booksavailable: "20",
  },
];