export const cartbooks = [
  {
    id: 1,
    imgsrc: "https://m.media-amazon.com/images/I/61Iz2yy2CKL._AC_UY218_.jpg",
    title: "The Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    genre: "Self-help",
    year: "2003",
    price: 90,
    booksavailable: "2",
  },
  {
    id: 8,
    imgsrc: "https://m.media-amazon.com/images/I/61eFRZCBBXL._AC_UY218_.jpg",
    title: "Naruto",
    author: "Masashi Kishimoto",
    genre: "Comics",
    year: "2010",
    price: 150,
    booksavailable: "1",
  },
  {
    id: 5,
    imgsrc: "https://m.media-amazon.com/images/I/61pHaR-LO6L._AC_UY218_.jpg",
    title: "Excel Formulas",
    author: "Michael Alexander",
    genre: "Computer",
    year: "2019",
    price: 85,
    booksavailable: "5",
  },
];